DmytroMorozTech/finalProject_fs12

- pom.xml
- src/frontend/README.md
- src/frontend/public/index.html
- src/frontend/src/index.js
- src/main/java/Main.java
- src/main/java/com/linkedin/app/Application.java
- src/main/java/com/linkedin/app/exception/ApiException.java
- src/main/java/com/linkedin/app/exception/ApiExceptionHandler.java
- src/main/java/com/linkedin/app/exception/ApiRequestException.java
- src/main/java/com/linkedin/app/exception/ConflictException.java
- src/main/java/com/linkedin/app/exception/ForbiddenException.java
- src/main/java/com/linkedin/app/exception/NotFoundException.java
- src/main/java/com/linkedin/app/utils/AuditConfig.java
- src/main/java/com/linkedin/app/utils/AuditorAwareImpl.java
- src/main/resources/application-local.yml
- src/main/resources/application.yml
1. The most important dependencies for the project were added to POM.xml. 
2. LTS version of Java was chosen for this project (Java 11).
2. H2 dependency was added to POM.xml;
3. application.yml (root properties file) and application-local.yml (works using in-memory H2 DB) were added.
4. Basic folders were created to form initial project structure.
> Added H2 dependency to POM.xml; Added basic project structure

- checkstyle_config.xml
- pom.xml
Changes were made to the file pom.xml and a checkstyle configuration file was created
> Checkstyle integration

- src/frontend/.eslintrc
1. Was installed in ESLint project.
2. The .eslintrc configuration file has been created.
3. Changes have been made to the Intellij IDEA settings in the ESLint item.
> Configure ESLint on front-end

- src/frontend/src/components/Main/Main.jsx
1. Added Header/Navbar components for front-end part
2. Added Main (Feed; Favorites; Messages; Profile) components for front-end part
> Featured header and main react files

- checkstyle_config.xml
- src/main/java/com/linkedin/app/exception/ApiExceptionHandler.java
1. Updated link in checkstyle_config.xml to be from a new secured source: https://checkstyle.org/dtds/configuration_1_3.dtd
2. Edited some values in <module name="Indentation"> in file checkstyle_config.xml.
I did it, because IDE automatically puts indentation of 4 whitespaces, while config (given by DAN-IT) requires 2 whitespaces.
All changes were made to reduce the number of errors produced by command **mvn validate**.
> Update of checkstyle_config.xml

- src/frontend/package-lock.json
- src/frontend/package.json
- src/frontend/src/components/Main/Favorites/Favorites.js
- src/frontend/src/components/Main/Feed/Feed.js
- src/frontend/src/components/Main/Main.js
- src/frontend/src/components/Main/MainLeft.js
- src/frontend/src/components/Main/MainRight.js
- src/frontend/src/components/Main/Messages/Messages.js
- src/frontend/src/components/Main/Profile/Profile.js
Contents of some React Components were removed by mistake during one of previous commits
> React Routing was fixed

- src/frontend/src/components/Main/Feed/Post/Post.js
- src/frontend/src/components/Main/Feed/Post/styles.js
- src/frontend/src/shared/LikeMiniIcon/styles.js
1. Part of the post was added (task 4).
2. Styles have been added for this part.
> Added part of post (task #4)

- src/frontend/src/components/Header/Header.js
- src/frontend/src/components/Header/Navbar/styles.js
- src/frontend/src/components/Header/styles.js
- src/frontend/src/components/Jobs/styles.js
- src/frontend/src/components/Main/Feed/styles.js
- src/frontend/src/components/Main/Messages/styles.js
- src/frontend/src/components/Main/Page404/Page404.js
- src/frontend/src/components/Main/Page404/style.js
- src/frontend/src/components/Main/Profile/styles.js
- src/frontend/src/components/Main/styleMain.js
- src/frontend/src/components/Main/styleMainLeft.js
- src/frontend/src/components/Modal/Modal.js
- src/frontend/src/components/Modal/styles.js
- src/frontend/src/components/Network/styles.js
- src/frontend/src/components/Notifications/styles.js
- src/main/java/com/danit/fs12/facade/CommentFacade.java
1. Fixed header when scrolling;
2. Set modal size
> -- fixed header and set modal size

- README.md
- src/frontend/src/components/Main/Feed/Post/Post.js
- src/frontend/src/components/Main/Feed/Post/styles.js
- src/frontend/src/components/Notifications/Notifications.js
- src/frontend/src/components/Notifications/styles.js
- src/frontend/src/shared/ThreeDots/TreeDots.js
- src/frontend/src/shared/ThreeDots/styles.js
1. Created shared ThreeDots.
2. Changed MoreHorizIcon on shared ThreeDots in Notifications and Post.
> Shared dots

- src/main/java/com/danit/fs12/beans/Convertor.java
> - ModelMapper was configured

- src/frontend/src/components/Main/Feed/AddNewPost/AddNewPost.js
- src/main/java/com/danit/fs12/entity/post/PostRq.java
- src/main/java/com/danit/fs12/facade/PostFacade.java
- src/main/java/com/danit/fs12/service/PostService.java
- Post can be created from UI Modal create Post.
- It will be saved in DB and in Redux
> Post can be created at frontend

- .github/workflows/ci.yml
- corrected the name of branch from master to main in ci.yml
> Fixed branch name in config

- src/frontend/src/components/Header/styles.js
- src/frontend/src/components/Main/Page404/Page404.js
- src/frontend/src/components/Main/Page404/styles.js
- removed small bug related to undesired Navbar offset when Modal window was appearing on the screen
- added link to the homepage for LinkedIn logo on page 404; centered lower text block
> - removed small bug related to undesired Navbar offset

- src/frontend/package-lock.json
- src/frontend/src/components/Main/Feed/Post/Post.js
- src/frontend/src/components/Main/Feed/Post/PostButton/NewCommentInput/Comment/Comment.js
- src/frontend/src/components/Main/Feed/Post/SeeMore/SeeMore.js
- src/frontend/src/components/Main/Feed/Post/SeeMore/styles.js
Created full functionality for "...see more" link in Comment and Post components.
> Created full functionality for "...see more" link in Comment and Post components.

- src/frontend/src/Theme/Theme.js
- src/frontend/src/components/Main/Feed/AddNewPost/AddNewPost.js
- src/frontend/src/components/Main/Feed/AddNewPost/styles.js
- src/frontend/src/components/Main/Feed/Post/PostButton/NewCommentInput/NewCommentInput.js
- src/frontend/src/components/Main/Feed/Post/PostButton/NewCommentInput/styles.js
- src/frontend/src/components/Modal/styles.js
- src/main/java/com/danit/fs12/entity/comment/Comment.java
- src/main/java/com/danit/fs12/entity/comment/CommentRq.java
- src/main/java/com/danit/fs12/entity/post/Post.java
- src/main/java/com/danit/fs12/entity/post/PostRq.java
1. Added validation to Comment input at frontend that will validate the maximum length of the input.
2. Added validation to Post input at frontend that will validate the maximum length of the input.
3. Fixed scroll on axis Y in modal for adding new Post.
> Inputs validation of Post and Comment

- src/frontend/src/components/Jobs/Jobs.js
- src/frontend/src/components/Jobs/JobsLeft/Item/Item.js
- src/frontend/src/components/Jobs/JobsLeft/Item/styles.js
- src/frontend/src/components/Jobs/JobsLeft/JobsLeft.js
- src/frontend/src/components/Jobs/JobsLeft/styles.js
- src/frontend/src/components/Jobs/JobsMain/JobsMain.js
- src/frontend/src/components/Jobs/JobsMain/styles.js
- src/frontend/src/components/Jobs/JobsRight/JobsRight.js
- src/frontend/src/components/Jobs/JobsRight/styles.js
- src/frontend/src/components/Jobs/styles.js
1. Added Grid to Jobs Page.
2. Added design of LeftTab on Jobs Page.
> Design LeftTab on Jobs Page

- src/frontend/src/App.js
- src/frontend/src/components/Login/loginCard/LoginCard.js
- src/frontend/src/services/httpService.js
- src/main/java/com/danit/fs12/service/UserService.java
- if user types in wrong email or password the server will respond with 403 error (Forbidden) and UI will draw a nice-looking notification.
- functionality of react-toastify can be reused in any place of the project, where you need to create some visual notification for user (for example, when you want to notify a user about some error that happened on the server; or warn him about smth., based on data returned from the server)
> - react-toastify package was added to project

- src/frontend/src/Theme/Theme.js
- src/frontend/src/components/Main/Feed/AddNewPost/styles.js
- src/frontend/src/components/Main/Feed/Post/PostButton/NewCommentInput/Comment/styles.js
- src/frontend/src/components/Main/Feed/Post/PostButton/NewCommentInput/styles.js
- src/frontend/src/components/Main/Feed/Post/styles.js
- src/frontend/src/components/Main/Feed/ShareBox/styles.js
- src/frontend/src/components/Main/Feed/UserWhoLiked/styles.js
- src/frontend/src/components/MainD/MainLeft/styles.js
- src/frontend/src/components/Network/Connections/Connections.js
- src/frontend/src/components/Network/Connections/ConnectionsMain/Connection/Connection.js
- src/frontend/src/components/Network/Connections/ConnectionsMain/Connection/styles.js
- src/frontend/src/components/Network/Connections/ConnectionsMain/ConnectionsMain.js
- src/frontend/src/components/Network/Connections/ConnectionsMain/styles.js
- src/frontend/src/components/Network/Connections/ConnectionsRight/ConnectionsRight.js
- src/frontend/src/components/Network/Connections/ConnectionsRight/styles.js
- src/frontend/src/components/Network/Connections/styles.js
- src/frontend/src/components/Network/NetworkLeft/Item/Item.js
- src/frontend/src/components/Network/NetworkLeft/Item/styles.js
- src/frontend/src/components/Network/NetworkLeft/NetworkLeft.js
- src/frontend/src/components/Notifications/NotificationsMain/Notification/styles.js
- src/frontend/src/components/UserData/styles.js
- src/frontend/src/routes/MainRoutes.js
1. Added design of ConnectionsMain.
2. Added design of Connection.
3. Small fixes of avatars width in Theme.
> Connection main page

- src/frontend/src/components/Jobs/JobsSmall/JobsAdditions/styles.js
- src/frontend/src/components/Network/Connections/Connections.js
- src/frontend/src/components/Network/Connections/ConnectionsMain/Connection/Connection.js
- src/frontend/src/components/Network/Connections/ConnectionsMain/Connection/ConnectionAddition/ConnectionAddition.js
- src/frontend/src/components/Network/Connections/ConnectionsMain/Connection/ConnectionAddition/styles.js
- src/frontend/src/components/Network/Connections/ConnectionsMain/Connection/styles.js
- src/frontend/src/components/Network/Connections/ConnectionsRight/ConnectionsRight.js
- src/frontend/src/components/Network/Connections/ConnectionsRight/styles.js
- src/frontend/src/shared/ImgToJobsPage/styles.js
- src/frontend/src/shared/PopupMenu/styles.js
1. Added design of ConnectionsRight.
2. Added menu to remove and implemented remove on the frontend.
> Connection right page

- src/frontend/src/components/Header/Navbar/Item/Item.js
Fixed navbar menu while clicking on profile button
> -- fixed navbar menu while clicking on profile button

- src/frontend/src/Theme/Theme.js
- src/frontend/src/components/Jobs/Jobs.js
- src/frontend/src/components/Jobs/JobsLeft/Item/Item.js
- src/frontend/src/components/Jobs/JobsLeft/JobsLeft.js
- src/frontend/src/components/Jobs/JobsSmall/styles.js
- src/frontend/src/components/Jobs/MyJobs/MyJobs.js
- src/frontend/src/components/Jobs/MyJobs/MyJobsLeft/MyJobsLeft.js
- src/frontend/src/components/Jobs/MyJobs/MyJobsLeft/styles.js
- src/frontend/src/components/Jobs/MyJobs/MyJobsMain/MyJobsMain.js
- src/frontend/src/components/Jobs/MyJobs/MyJobsMain/SavedVacancy/SavedVacancy.js
- src/frontend/src/components/Jobs/MyJobs/MyJobsMain/SavedVacancy/SavedVacancyAdditions/Item/Item.js
- src/frontend/src/components/Jobs/MyJobs/MyJobsMain/SavedVacancy/SavedVacancyAdditions/Item/styles.js
- src/frontend/src/components/Jobs/MyJobs/MyJobsMain/SavedVacancy/SavedVacancyAdditions/SavedVacancyAdditions.js
- src/frontend/src/components/Jobs/MyJobs/MyJobsMain/SavedVacancy/SavedVacancyAdditions/styles.js
- src/frontend/src/components/Jobs/MyJobs/MyJobsMain/SavedVacancy/styles.js
- src/frontend/src/components/Jobs/MyJobs/MyJobsMain/styles.js
- src/frontend/src/components/Jobs/MyJobs/MyJobsRight/MyJobsRight.js
- src/frontend/src/components/Jobs/MyJobs/MyJobsRight/styles.js
- src/frontend/src/components/Jobs/MyJobs/styles.js
- src/frontend/src/routes/MainRoutes.js
1. Added Link to My Jobs Page on Jobs Left.
2. Added My Jobs Left on My Jobs Page.
3. Added My Jobs Main on My Jobs Page.
4. Added My Jobs Right on My Jobs Page.
5. Added SavedVacancy component.
6. Added SaveVacancyAdditions component.
7. Added adaptive version on My Jobs Page.
> Added My Jobs Page

- src/frontend/src/components/Main/Feed/Feed.js
- src/frontend/src/redux/Comment/commentActions.js
- src/frontend/src/redux/Message/messageActions.js
- src/frontend/src/redux/Post/postActions.js
- src/frontend/src/redux/Profile/profileActions.js
- src/frontend/src/redux/User/userActions.js
- src/frontend/src/services/headersService.js
- src/frontend/src/services/httpService.js
1. Added header data into axios interceptors to intercept any requests.
2. Removed getHeader() method from all axios requests.
> Added header data into axios interceptors

- src/main/java/com/danit/fs12/exception/AuthenticationException.java
- src/main/java/com/danit/fs12/service/UserService.java
Added missed checking of possible NullPointerException in UserService on getActiveUser() method.
> -- added NPE checking on getActiveUser()

- src/frontend/src/App.js
- src/frontend/src/components/Login/Login.js
- src/frontend/src/redux/User/userActions.js
- src/frontend/src/redux/User/userReducer.js
- src/frontend/src/routes/ProtectedRoutes.js
- fixed an issue related to the excessive rendering of Login page when refreshing the page (by pressing F5 in browser)
- added new case LOADING_USERS to userReducer.js
> removed excessive rendering of Login page

- src/frontend/src/components/Login/loginCard/LoginCard.js
- src/frontend/src/components/Network/NetworkMain/Invitation/Invitation.js
- src/frontend/src/components/Network/NetworkMain/Invitation/styles.js
- src/frontend/src/components/Network/NetworkMain/MiniProfile/MiniProfile.js
- src/frontend/src/components/Network/NetworkMain/MiniProfile/styles.js
- src/frontend/src/components/Network/styles.js
- src/frontend/src/redux/Post/postReducer.js
1. Fixed Network adaptive on screen width 320px.
2. Fixed a bug in INCREMENT_COMMENTS_COUNTER_FOR_POST.
> Fix network adaptive

- src/main/java/com/danit/fs12/entity/user/User.java
- src/main/java/com/danit/fs12/entity/user/UserRs.java
- removed unnecessary field that caused an infinite loop (Jackson tried to serialize this field and that started an infinite loop);
- removed 1 unused method
> fixed bugs

- src/frontend/src/components/Network/InvitationManager/InvitationManagerReceived.js
- src/frontend/src/components/Network/InvitationManager/InvitationManagerSent.js
- src/frontend/src/components/Network/Network.js
- src/frontend/src/redux/Network/networkActions.js
- src/main/java/com/danit/fs12/service/UserService.java
- src/main/java/com/danit/fs12/utils/ForgotMailLetter.java
Fixed problem with infinite loop in invitations
> Fixed infinite loop in invitations

- src/frontend/src/components/OrganizationPage/OrganizationMain/styles.js
- src/main/resources/db/changelog/changes/003.sql
- src/main/resources/db/changelog/master.yaml
1. Added 003.sql.
2. Fixed master.yaml.
> Fixed bug of Organization.

- src/frontend/src/components/ForgotPass/ForgotPage/ForgotPage.js
- src/frontend/src/components/Main/Feed/Post/PostButton/PostButtons.js
- src/frontend/src/components/Main/Feed/Post/PostButton/SendPostLink/SendPostLink.js
- src/frontend/src/components/Register/RegisterPage/RegisterPage.js
- src/frontend/src/redux/User/userActions.js
- src/frontend/src/redux/User/userReducer.js
- src/main/java/com/danit/fs12/controller/AuthController.java
- src/main/java/com/danit/fs12/controller/FrontendController.java
- src/main/java/com/danit/fs12/entity/user/User.java
- src/main/java/com/danit/fs12/facade/UserFacade.java
- src/main/java/com/danit/fs12/security/config/SecurityConfig.java
- src/main/java/com/danit/fs12/security/oauth2/OAuth2LoginSuccessHandler.java
- src/main/java/com/danit/fs12/service/UserService.java
- created FrontendController for redirection to index.html
- renamed endpoint in AuthController: /activeuser -> /active_user
- small refactoring of "/signup" endpoint in AuthController
- replaced logic for generation of post link inside of React app
- fixed some security data and added preloader on ForgotPage component
> Fix bugs 001

- src/frontend/src/components/ProfilePage/ProfileMain/ProfileMain.js
- src/frontend/src/components/ProfilePage/ProfileMain/ProfileMain.test.js
- src/frontend/src/components/ProfilePage/ProfileMain/__snapshots__/ProfileMain.test.js.snap
- src/frontend/src/components/ProfilePage/ProfileRight/ProfileRight.js
- src/frontend/src/components/ProfilePage/ProfileRight/ProfileRight.test.js
- src/frontend/src/components/ProfilePage/ProfileRight/__snapshots__/ProfileRight.test.js.snap
1. Tested ProfileMain component.
2. Tested ProfileRight component.
> Test profile page components

- src/frontend/src/components/Main/Feed/Feed.js
- src/frontend/src/components/Main/Feed/Post/__snapshots__/Post.test.js.snap
- src/frontend/src/components/Main/Feed/__snapshots__/Feed.test.js.snap
- src/frontend/src/components/Main/MainLeft/MainLeft.js
- src/frontend/src/components/Main/MainLeft/__snapshots__/MainLeft.test.js.snap
- src/frontend/src/components/Main/SmallMySavedPosts/SmallMySavedPosts.js
- src/frontend/src/components/Main/SmallMySavedPosts/SmallMySavedPosts.test.js
- src/frontend/src/components/Main/SmallMySavedPosts/__snapshots__/SmallMySavedPosts.test.js.snap
- src/frontend/src/components/Main/SmallMySavedPosts/styles.js
- src/frontend/src/components/Notifications/NotificationsMain/Notification/__snapshots__/Notification.test.js.snap
- src/frontend/src/components/Notifications/SmallNotification/SmallNotification.js
- src/frontend/src/components/Notifications/SmallNotification/SmallNotification.test.js
- src/frontend/src/components/Notifications/SmallNotification/__snapshots__/SmallNotification.test.js.snap
1. Added SmallMySavedPosts component.
2. Fixed SmallNotification component.
3. Tested SmallNotification, SmallMySavedPosts components.
> SmallNotification and SmallMySavedPosts 

- src/frontend/src/components/Messages/Chat.js
- src/frontend/src/components/Messages/ChatsList.js
- src/frontend/src/components/Messages/NewChat.js
Deleted green dots that show if user is online and fixed date title line in messages
> Fix bugs 004

- src/frontend/src/components/Main/Feed/AddNewPost/AddNewPost.js
- src/frontend/src/components/Main/Feed/AddNewPost/__snapshots__/AddNewPost.test.js.snap
- src/frontend/src/components/Main/Feed/Post/__snapshots__/Post.test.js.snap
- src/frontend/src/components/Notifications/NotificationsMain/Notification/__snapshots__/Notification.test.js.snap
- src/frontend/src/components/ProfilePage/ProfileModal/CertificationModal/CertificationModal.js
- src/frontend/src/components/Register/RegisterPage/__snapshots__/RegisterPage.test.js.snap
- src/frontend/src/components/Register/RegisterPage/styles.js
- src/frontend/src/redux/Image/imageActions.test.js
- src/frontend/src/shared/PopupMenu/PopupMenu.js
- src/frontend/src/shared/PopupMenu/__snapshots__/PopupMenu.test.js.snap
- src/frontend/src/shared/PopupMenu/styles.js
1. Fixed styles of RegisterPage.
2. Removed LightTooltip 'Add a document'.
3. Fixed styles of PopupMenu.
4. Fixed styles of CertificationModal.
5. Tested imageActions.
> Fix bugs 005
